import { Inter } from "next/font/google";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Techify AI customer support",
=======
  title: "Techify support",
  description: "Generated by create next app",
>>>>>>> 22e7d3d8f36cc61bfc9db016d61f8113d5b96b48
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
